github: []
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  parse_span_html: true
  html_to_native: true
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
 
