github: []
encoding: UTF-8
markdown: 1
kramdown:
  input: kramdown
  hard_wrap: false
  parse_block_html: false
  parse_span_html: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
 
