github: []
encoding: UTF-8
kramdown:
  input: kramdown
  hard_wrap: true
  parse_block_html: true
  parse_span_html: true
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
 
